"""Add financial snapshots table

Revision ID: 00d7ee12c280
Revises: 3050e5dd5d04
Create Date: 2025-08-06 01:07:42.194357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d7ee12c280'
down_revision: Union[str, Sequence[str], None] = '3050e5dd5d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('inventory_value', sa.Numeric(), nullable=False),
    sa.Column('goods_in_transit_value', sa.Numeric(), nullable=False),
    sa.Column('total_assets', sa.Numeric(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_snapshots')
    # ### end Alembic commands ###