"""add_sdek_fields_to_supplier_orders

Revision ID: 43077a41ae05
Revises: e5f1ac3a674f
Create Date: 2025-09-09 14:36:34.106211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43077a41ae05'
down_revision: Union[str, Sequence[str], None] = 'e5f1ac3a674f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_orders', sa.Column('sdek_order_uuid', sa.String(length=255), nullable=True))
    op.add_column('supplier_orders', sa.Column('sdek_track_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_orders', 'sdek_track_number')
    op.drop_column('supplier_orders', 'sdek_order_uuid')
    # ### end Alembic commands ###
