"""create_return_shipment_tables

Revision ID: 5d960d026195
Revises: ab8c4137fe4e
Create Date: 2025-09-09 20:24:40.656107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d960d026195'
down_revision: Union[str, Sequence[str], None] = 'ab8c4137fe4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_shipments', sa.Column('sdek_order_uuid', sa.String(length=255), nullable=True))
    op.add_column('return_shipments', sa.Column('sdek_track_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_shipments', 'sdek_track_number')
    op.drop_column('return_shipments', 'sdek_order_uuid')
    # ### end Alembic commands ###
