"""Add sdek_status field to orders and shipments

Revision ID: 667100551065
Revises: 6b1c06d71a62
Create Date: 2025-09-17 17:16:28.711564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667100551065'
down_revision: Union[str, Sequence[str], None] = '6b1c06d71a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_shipments', sa.Column('sdek_status', sa.String(length=255), nullable=True))
    op.add_column('supplier_orders', sa.Column('sdek_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_orders', 'sdek_status')
    op.drop_column('return_shipments', 'sdek_status')
    # ### end Alembic commands ###
