"""Add display_order to checklist_items

Revision ID: 6b1c06d71a62
Revises: c3c18d49eb16
Create Date: 2025-09-17 14:36:48.912275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c06d71a62'
down_revision: Union[str, Sequence[str], None] = 'c3c18d49eb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('display_order', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_items', 'display_order')
    # ### end Alembic commands ###
