"""Add loaner pool to EnumShop

Revision ID: 9a097d59660d
Revises: d22f05403a1b
Create Date: 2025-08-04 17:08:12.750947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a097d59660d'
down_revision: Union[str, Sequence[str], None] = 'd22f05403a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'storage_location',
               existing_type=sa.Enum('СКЛАД', 'ВИТРИНА', name='enumshop', native_enum=False),
               type_=sa.Enum('СКЛАД', 'ВИТРИНА', 'ПОДМЕННЫЙ_ФОНД', name='enumshop', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'storage_location',
               existing_type=sa.Enum('СКЛАД', 'ВИТРИНА', 'ПОДМЕННЫЙ_ФОНД', name='enumshop', native_enum=False),
               type_=sa.Enum('СКЛАД', 'ВИТРИНА', name='enumshop', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###