"""Add address field to Supplier

Revision ID: c3c18d49eb16
Revises: 5d960d026195
Create Date: 2025-09-17 11:01:55.204252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c18d49eb16'
down_revision: Union[str, Sequence[str], None] = '5d960d026195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'address')
    # ### end Alembic commands ###
