"""Add loaner_log table

Revision ID: d22f05403a1b
Revises: a6eaff375c97
Create Date: 2025-08-04 16:18:21.745893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22f05403a1b'
down_revision: Union[str, Sequence[str], None] = 'a6eaff375c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loaner_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('loaner_phone_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loaner_phone_id'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loaner_log')
    # ### end Alembic commands ###