"""Add dividend calculations table

Revision ID: d8736e127733
Revises: aebe9ecf0297
Create Date: 2025-09-04 00:57:24.429899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8736e127733'
down_revision: Union[str, Sequence[str], None] = 'aebe9ecf0297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('start_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('end_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Numeric(), nullable=False),
    sa.Column('reinvestment_amount', sa.Numeric(), nullable=False),
    sa.Column('dividends_amount', sa.Numeric(), nullable=False),
    sa.Column('owner_dividends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['end_snapshot_id'], ['financial_snapshots.id'], ),
    sa.ForeignKeyConstraint(['start_snapshot_id'], ['financial_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_notifications_user_id_is_read'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_waiting_list_status'), table_name='waiting_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_waiting_list_status'), 'waiting_list', ['status'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id_is_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_table('dividend_calculations')
    # ### end Alembic commands ###
