"""Change snapshot_date to datetime and remove unique constraint

Revision ID: de5190a843f1
Revises: 00d7ee12c280
Create Date: 2025-08-06 01:33:38.100245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5190a843f1'
down_revision: Union[str, Sequence[str], None] = '00d7ee12c280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_snapshots', 'snapshot_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('financial_snapshots_snapshot_date_key', 'financial_snapshots', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_snapshots', 'snapshot_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_unique_constraint('financial_snapshots_snapshot_date_key', 'financial_snapshots', ['snapshot_date'])
    # ### end Alembic commands ###