"""Add user_id to cash_flow

Revision ID: e5f1ac3a674f
Revises: d8736e127733
Create Date: 2025-09-04 01:22:33.367179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f1ac3a674f'
down_revision: Union[str, Sequence[str], None] = 'd8736e127733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cash_flow', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cash_flow', type_='foreignkey')
    op.drop_column('cash_flow', 'user_id')
    # ### end Alembic commands ###
