"""Create initial schema from models

Revision ID: eabb6705ef0f
Revises: 
Create Date: 2025-08-01 23:43:46.913227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eabb6705ef0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accessories', 'category_accessory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accessories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accessories', 'barcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accessories_model', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accessories_model', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accessories_model', 'model_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('battery_test', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('battery_test', 'device_inspection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('battery_test', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('battery_test', 'start_battery_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('battery_test', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('battery_test', 'end_battery_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('battery_test', 'test_duration',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('battery_test', 'battery_drain',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('cash_flow', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cash_flow', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cash_flow', 'operation_categories_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cash_flow', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cash_flow', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('cash_flow', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cash_flow', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('category_accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category_accessories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checklist_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('checklist_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('colors', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('colors', 'color_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('counterparties', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('counterparties', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('counterparties', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('currency', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('currency', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('device_inspection', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_inspection', 'phone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device_inspection', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device_inspection', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'device_inspection', 'phones', ['phone_id'], ['id'])
    op.alter_column('inspection_results', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inspection_results', 'device_inspection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inspection_results', 'checklist_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inspection_results', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_name', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('model_name', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('model_number', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('model_number', 'name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('models', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('models', 'model_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('models', 'storage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('models', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('operation_categories', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('operation_categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('permissions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permissions', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('phones', 'technical_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ОЖИДАЕТ_ПРОВЕРКУ', 'НА_ТЕСТЕ_АККУМУЛЯТОРА', 'НА_УПАКОВКЕ', 'УПАКОВАН', 'БРАК', 'НА_ПРОВЕРКЕ', name='techstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('product_type', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_type', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('retail_price_accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('retail_price_accessories', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('retail_price_accessories', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('retail_price_accessories', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('retail_prices_phones', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('retail_prices_phones', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('retail_prices_phones', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('retail_prices_phones', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sale_details', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sale_details', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_details', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_details', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.create_foreign_key(None, 'sale_details', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(None, 'sale_details', 'warehouse', ['warehouse_id'], ['id'])
    op.alter_column('shops', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shops', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shops', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('storage', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('storage', 'storage',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('supplier', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supplier', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('supplier_order_details', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supplier_order_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_order_details', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('supplier_order_details', 'supplier_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'supplier_order_details', 'supplier_orders', ['supplier_order_id'], ['id'])
    op.alter_column('supplier_orders', 'payment_status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('НЕ_ОПЛАЧЕН', 'ЧАСТИЧНО_ОПЛАЧЕН', 'ОПЛАЧЕН', name='orderpaymentstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'НЕ_ОПЛАЧЕН'::character varying"))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('waiting_room', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('waiting_room', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waiting_room', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waiting_room', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waiting_room', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waiting_room', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supplier_orders', 'payment_status',
               existing_type=sa.Enum('НЕ_ОПЛАЧЕН', 'ЧАСТИЧНО_ОПЛАЧЕН', 'ОПЛАЧЕН', name='orderpaymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'НЕ_ОПЛАЧЕН'::character varying"))
    op.drop_constraint(None, 'supplier_order_details', type_='foreignkey')
    op.alter_column('supplier_order_details', 'supplier_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_order_details', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('supplier_order_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_order_details', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supplier', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('supplier', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('storage', 'storage',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('storage', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shops', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('shops', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shops', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'sale_details', type_='foreignkey')
    op.drop_constraint(None, 'sale_details', type_='foreignkey')
    op.alter_column('sale_details', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('sale_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_details', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_details', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_details', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('retail_prices_phones', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('retail_prices_phones', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('retail_prices_phones', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('retail_prices_phones', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('retail_price_accessories', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('retail_price_accessories', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('retail_price_accessories', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('retail_price_accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_type', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_type', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('phones', 'technical_status',
               existing_type=sa.Enum('ОЖИДАЕТ_ПРОВЕРКУ', 'НА_ТЕСТЕ_АККУМУЛЯТОРА', 'НА_УПАКОВКЕ', 'УПАКОВАН', 'БРАК', 'НА_ПРОВЕРКЕ', name='techstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('permissions', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('operation_categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('operation_categories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('models', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('models', 'storage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('models', 'model_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('models', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('model_number', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('model_number', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('model_name', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('model_name', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inspection_results', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('inspection_results', 'checklist_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inspection_results', 'device_inspection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inspection_results', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'device_inspection', type_='foreignkey')
    op.alter_column('device_inspection', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device_inspection', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device_inspection', 'phone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device_inspection', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('currency', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('currency', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('counterparties', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('counterparties', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('counterparties', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('colors', 'color_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('colors', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('checklist_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('checklist_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category_accessories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('category_accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cash_flow', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cash_flow', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cash_flow', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('cash_flow', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cash_flow', 'operation_categories_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cash_flow', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cash_flow', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('battery_test', 'battery_drain',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('battery_test', 'test_duration',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('battery_test', 'end_battery_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('battery_test', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('battery_test', 'start_battery_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('battery_test', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('battery_test', 'device_inspection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('battery_test', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accounts', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accessories_model', 'model_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accessories_model', 'accessory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accessories_model', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accessories', 'barcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accessories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accessories', 'category_accessory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accessories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
